FROM rockylinux:8

RUN dnf -y install openssh-server sudo python3 ksh && dnf clean all

RUN useradd -m -s /bin/bash aix && echo "aix:aix" | chpasswd && \
    usermod -aG wheel aix && \
    echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN mkdir -p /var/run/sshd /opt/mock/aix/bin /opt/mock/aix/data /etc/profile.d && ssh-keygen -A

COPY sshd_config /etc/ssh/sshd_config
COPY profile.d/mock-aix.sh /etc/profile.d/mock-aix.sh
COPY bin/ /opt/mock/aix/bin/
COPY data/ /opt/mock/aix/data/
RUN bash -lc 'for f in /opt/mock/aix/bin/*; do sed -i "s/\r$//" "$f"; done'

RUN chmod +x /opt/mock/aix/bin/_shim_template && chmod +x /opt/mock/aix/bin/lslpp /opt/mock/aix/bin/oslevel /opt/mock/aix/bin/lsdev /opt/mock/aix/bin/errpt /opt/mock/aix/bin/df /opt/mock/aix/bin/uname

EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
